//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Levels/level1.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// LDtk Enum for level1
/// </summary>
public enum Biome
{
    Grass,
    DarkForest
}

/// <summary>
/// LDtk Enum for level1
/// </summary>
public enum PostProcessProfile
{
    Scanlines_Off,
    Scanlines_Low,
    Scanlines_High,
    Scanlines_Max
}

/// <summary>
/// LDtk Enum for level1
/// </summary>
public enum Light
{
    High,
    Medium,
    Low,
    None
}